### PR TITLE
[WIP] To be rebased into smaller PRs: Improving readability and adding citations: hyperref, cross-references, extra citations; clarifications (e.g. minor rewording and footnotes); list of maths symbols; fixed formatting e.g. subscripts to \mathrm font; archive links; grammar fixes (e.g. complete sentences like in the tables); readme: omitted yellowpaper.io and added more details on how to build.

### PR DESCRIPTION
**Pull request by jamesray1**
Too big a PR, rebasing to smaller PRs:
- [x] PR #373: rebased commits 2 (97b534cd876111602e51eaf3d56864807096ccc4) and 3 (e71e30e58c451724929bd33d2da88608b26923c7), and implicitly commit 1.
- [ ] ~~PR #371: Merged 59bcf73, 51b0afb3393bce05c7143b60cb80218dc757f56d, b2f7605, 08172f4 and 9f03f5896ba66c4cf27658cf4545988a020fdc53 and 60ea6865340e20b68cd648f941d4e9941886d0fc to local Clarifications branch, but got mixed up with other commits. All commits: numbers 4 (08172f4) to 17 (9f03f58). It's probably better to rebase into still smaller PRs.~~
- [ ] ~~PR #370: Merged commits 7 (9072ca8bf5b2205b296fb6de2d04a279b48e3983) and 11, (3feff95f17e7985e8c0b5c1a5dba51e80b608894), and implicitly commit 10 (4710b8e), which was overwritten by 11. Done on Github, but another commit needs to be merge 1e7849255f97ad45b8f5249399cb95f84f782301~~
- [ ] rebase other commits

### CODE REVIEW

**Comment by jamesray1** [comment]
For the error in this build: https://travis-ci.org/ethereum/yellowpaper/builds/281883138?utm_source=github_status&utm_medium=notification

> ! Package inputenc Error: Unicode char \u8:  not set up for use with LaTeX.

see [here](https://tex.stackexchange.com/questions/4268/inputenc-error-unicode-char-u8-error-while-trying-to-write-a-degree-symbol#4270).

**Comment by jamesray1** [comment]
As expected for a680e16, removing the e with the umlaut didn't help. The build still fails.

**Comment by jamesray1** [comment]
I just highlighted the white space in the build error, and inspected the element to find that it contains an ellipsis. Also if I try to view the page source this is included:

<h1>Hey there!</h1>
--
  | <p>Looks like you have JavaScript disabled.</p>
  | <p>The Travis CI webclient needs JavaScript to work properly.</p>
  | <h2>Please enable JavaScript to get the best Travis CI experience.</h2>
  | <h3>Thank you!</h3>

**Comment by axic** [comment]
I think you'll have better chances at review and merging this if it is split into smaller pull requests.

**Comment by jamesray1** [comment]
Maybe you're right.

**Comment by jamesray1** [comment]
This is the PDF that produces from my local repo.
[Paper.pdf](https://github.com/ethereum/yellowpaper/files/1348380/Paper.pdf)

It produced before all the dependencies that I added on the Github repo were added. I have never got the `! Package inputenc Error: Unicode char \u8: not set up for use with LaTeX.` error when building on my local repo.

**Comment by jamesray1** [comment]
If I split into smaller pull requests I think I would need to have a separate branch for each pull request, or wait until each pull request is merged before making another one.

**Comment by jamesray1** [comment]
What's confusing is that commits between 23 Sept and 30 Sept don't show whether the Travis build passed or failed.

**Comment by jamesray1** [comment]
Hooray, bbf6453 got the build to pass!

**Comment by jamesray1** [comment]
Ah when I run ./build.sh in my local repo this is included at the start of the output:

> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/small2e.tex

But the Travis build has:

> This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./Paper.tex
LaTeX2e <2011/06/27>

So clearly TeX Live needs to be updated for this online repo.

Furthermore I also installed the latest version:

> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/small2e.tex
LaTeX2e <2017-04-15>

**Comment by jamesray1** [comment]
I couldn't find how to change the "dist" as shown in the Travis CI build config from Trusty to Xenial, which [allows installing texlive via the command line](http://tipsonubuntu.com/2016/09/16/install-tex-live-2016-ubuntu-16-04-14-04/).

**Comment by jamesray1** [comment]
Note that there are also options to install the latest version, e.g. [here](https://www.tug.org/texlive/acquire-mirror.html).

**Comment by jamesray1** [comment]
So unfortunately it seems that to be able to test what the PDF looks like, we need to install TeX Live 2013/Debian, or upgrade the online Travis CI build to a later OS.

**Comment by pirapira** [comment]
The build is failing again.

**Comment by jamesray1** [comment]
Closing for now because the references need to be fixed. (There are several Wikipedia and other references that aren't advisable for citing.)

**Comment by jamesray1** [comment]
I'll leave it open but I will make further changes, so probably best to wait until that's done before merging, otherwise I'd be submitting another PR.

**Comment by jamesray1** [comment]
It's been over a week to make changes to the references that took less than half an hour... It probably would've been better to do this earlier but I've had a busy week.

**Comment by pirapira** [comment]
I cannot review this size of a PR.  Please split it into smaller ones.

**Comment by jamesray1** [comment]
What level of granularity do you require for a PR? In other words, what's the maximum number of lines changed you'd accept for a PR? I don't want to keep having to go back and forth. It's better to know what your criteria are up front.

**Comment by pirapira** [comment]
I don't have a clearcut standard.  PR reviewing is a back-and-forth process.  It's harder to review when a PR mixes changes of different purposes (e.g. removing certain kind of references vs. adding hyperlinks).

**Comment by jamesray1** [comment]
OK I'll have a PR for each item in the list, where possible. But any dependencies will have to go together, such as the cross-references and URLs in the note field in the biblio file are dependent on the hyperref.

**Comment by jamesray1** [comment]
I don't know what the most efficient way to create multiple PRs is before any are merged. I'll try having multiple branches with one PR for each branch.

**Comment by jamesray1** [comment]
I'm trying to use Git with `git branch <branchname>` and `git cherrypick <commithash>` or `git cherrypick <commithash>..<latercommithash>, plus a [mergetool](https://stackoverflow.com/questions/19830464/git-cherry-pick-and-conflicts#19830536).

**Comment by pirapira** [comment]
@jamesray1 no idea about the nibbles and the branches.  Sorry.

**Comment by jamesray1** [comment]
OK it's a bit ambiguous so maybe we should confirm what it means. Maybe Gavin Wood might know, but I'm not sure if I should tag him.

**Comment by pirapira** [comment]
I think the current sentence is at least hard to read.  Will you create an issue about it?

**Comment by jamesray1** [comment]
I think I already have.

**Comment by jamesray1** [comment]
https://github.com/ethereum/yellowpaper/issues/331

**Pull request closed without merging**
