### PR TITLE
Metroplis: EIP 101 big-modexp precompile

### PR DESCRIPTION
**Pull request by pirapira**
If merged, this would solve #235 as part of the Metropolis changes #229.

This is a re-incarnation of #258.  Comments given there are addressed.

### CODE REVIEW

**Comment by axic** [comment]
I wonder if it would make sense including the accepted EIP numbers next to the precompiles? Sort of keeping a history which EIP introduced a certain change.

**Comment by pirapira** [comment]
@axic I'll discuss that with @gavofyork when I see him next time.

**Comment by gavofyork** [comment]
i think the EIP process is documentation enough - YP is meant as a clean expression of the current state of the Ethereum protocol, not a chronicle of how it got there.

**Comment by pirapira** [comment]
The commit history should be cleaned, but as a precaution against EIP changes before Metropolis, some intermediate commits are still left.

**Comment by pirapira** [comment]
This PR should now target `master` because now `master` is the Byzantium branch.

**Pull request closed without merging**
