### PR TITLE
Updates difficulty calculation per EIP PR 1240

### PR DESCRIPTION
**Pull request by MicahZoltu**
EIP number TBD, will update once decided.
https://github.com/ethereum/EIPs/pull/1240

### CODE REVIEW

**Comment by nicksavers** [comment]
@MicahZoltu Do you want to keep this around?

This would require a fork. The current `master` branch describes Byzantium. And as far as I'm aware, it is not planned for the `constantinople` branch either.

It's fine to keep this PR around for as long as the EIP is in Draft in case it gets Accepted and included in a fork, but for now I don't expect to merge it.

**Comment by MicahZoltu** [comment]
I'm somewhat ambivalent to closing this or keeping it open.  I believe I was outvoted for this change, so perhaps I should just close the PR as well (even though I still think it is a good idea).

**Comment by nicksavers** [comment]
Then I'd recommend to close it for now and create a new PR into a branch for the fork in which it will be included.

**Comment by yperbasis** [comment]
Closing since EIP-1240 hasn't been accepted.

**Pull request closed without merging**
