### PR TITLE
Add table of versions in BRANCHES.md

### PR DESCRIPTION
**Pull request by pirapira**
The repository is organized so that every protocol version has a branch.  This PR documents those branches in README.md.

### CODE REVIEW

**Comment by pirapira** [comment]
Perhaps I should add block numbers.

**Comment by nicksavers** [comment]
Perhaps this table is better suited for a separate file called ` BRANCHES`, with a link to it from the README. And yes, including block-numbers would help understand the order in which to compare the branches and implementing a client that supports the full history.

**Comment by pirapira** [comment]
I separated the branch table into a separate file.  I also added the block numbers in the table.

**Comment by jamesray1** [comment]
May we please also put links to each version of the PDF?

**Comment by jamesray1** [comment]
I'm confused. https://github.com/ethereum/EIPs/blob/master/EIPS/eip-606.md says that the fork block number for Homestead for the main net is >=1,150,000, not 1 as is stated here.

**Comment by pirapira** [comment]
@jamesray1 please open a new issue about a link to each version of PDF.

**Comment by pirapira** [comment]
@jamesray1 I think I forgot `frontier` in the table.

**Pull request merged**
