### PR TITLE
hypertargets lines 100–199

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by pirapira** [comment]
Why does Travis fail?

**Comment by jamesray1** [comment]
I don't know. The error in the build is odd.

```
! Missing $ inserted.
<inserted text> 
                $
l.104 ...ate_transition}{Upsilon_state_transition}
```
\hypertarget{Upsilon_state_transition}{Upsilon_state_transition} isn't in math mode.

**Comment by jamesray1** [comment]
Now the error has changed:
```
! LaTeX Error: Something's wrong--perhaps a missing \item.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.199 \item[nonce]
                   A scalar value equal to the number of transactions sent f...
```

**Comment by jamesray1** [comment]
With the new `\nop` command created in the preamble, after this PR is merged I'll be able to similarly replace \hypertarget{foo}{} with \nop{foo} in other PRs, and move it to the same line to direct to, which it will do.

**Comment by pirapira** [comment]
@jamesray1 somehow the name `nop` means very little.  Can you use a more informative name?

**Comment by jamesray1** [comment]
OK let's decide before I make the change. How about furl? It's short for fixed URL (and conveniently pronounceable as one word).

**Comment by pirapira** [comment]
It's a target, or a marker, or a destination, or https://github.com/ethereum/yellowpaper/pull/458#issuecomment-360785506 .

**Comment by jamesray1** [comment]
OK OK I didn't think that through. What about dest, or targ, or mark?

**Comment by pirapira** [comment]
linkdest?

**Comment by jamesray1** [comment]
OK let's use that.

**Pull request merged**
