### PR TITLE
Remove trace of Homestead transition

### PR DESCRIPTION
**Pull request by pirapira**
I heard @gavofyork wanted the Yellow Paper to describe the newest protocol only. There would be a new version of the paper for a new version of the protocol. This PR is an attempt to remove the description of the protocol before the Homestead transition.

### CODE REVIEW

**Comment by axic** [comment]
So basically a list of yellowpaper *releases* for particular hard forks is required in order to write a client from scratch. Such a list should be included somewhere in the paper.

**Comment by axic** [comment]
I actually like the proposal #228.

**Comment by pirapira** [comment]
When I talked about that @gavofyork created `metropolis` branch in this repository.  One way forward is, I guess, to create branches `frontier` `homestead` `spurious_dragon` and `metropolis` in this repo, and the newer versions refer to the historical block numbers and the branch names in this repo.

**Comment by pirapira** [comment]
#228 is about adding an appendix about historical protocol changes.

**Pull request merged**
