### PR TITLE
EIP-3607: transactions from senders with deployed contract are forbidden

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Draft PR for EIP-3607 (https://eips.ethereum.org/EIPS/eip-3607).
Waits for 3607 to be approved by the Core Devs

cc @dankrad

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM (text-wise, haven't reviewed the rendered diff)

**Review by yperbasis — CHANGES_REQUESTED** [review]
The condition should be
```
\boldsymbol{\sigma}[S(T)]_{\mathrm{c}} = \texttt{KEC}\big( () \big)
```
i.e. that sender's **codeHash** is that of an empty string.
For example, check the definition of an empty account in Eq (14).


`I_{\mathbf{b}}` isn't correct: it refers to initialising code, not sender's code.

Also, please add the condition to the validity Eq (59).

**Comment by MariusVanDerWijden** [comment]
@yperbasis we discussed the change on ACD and decided to go with empty codehash as the condition instead of codesize as you proposed. Will un-draft the PR once the changes are merged into the EIP, the tests and the EIP is moved into Final

**Comment by holiman** [comment]
See https://github.com/ethereum/go-ethereum/pull/23002#issuecomment-872282874 

Basically, a client implementing this change must be careful. If the same 'check' as `EXTCODEHASH` is reused for this check, then it needs to _allow_ both `0x000..` and `emptyCodeHash`. Because a transaction from an account that did not previously exist _is_ historically OK, if a miner accepts a gasPrice of zero. Which has happened.

**Comment by yperbasis** [comment]
> See [ethereum/go-ethereum#23002 (comment)](https://github.com/ethereum/go-ethereum/pull/23002#issuecomment-872282874)
> 
> Basically, a client implementing this change must be careful. If the same 'check' as `EXTCODEHASH` is reused for this check, then it needs to _allow_ both `0x000..` and `emptyCodeHash`. Because a transaction from an account that did not previously exist _is_ historically OK, if a miner accepts a gasPrice of zero. Which has happened.

Should we include EIP-3607 into London or Shanghai then instead of applying it retroactively?

**Review by yperbasis — APPROVED** [review]

**Comment by yperbasis** [comment]
Shall we merge it, given that it's already in geth (https://github.com/ethereum/go-ethereum/pull/23303) ?

**Pull request merged**
