### PR TITLE
[WIP] hyperref package

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
I have gone and added more commits to one PR rather than reduced them!

@pirapira is there any chance that you could review by adding comments to the diff and checkmarks of where you are up to? That would be a lot less time-consuming for me.

**Comment by pirapira** [comment]
@jamesray1 At the end, I cannot merge this, but I need to convince @gavofyork .  I don't know his limit of complexity per PR.

**Comment by jamesray1** [comment]
This PR is not suitable for merging, the other one #365 should be more suitable.

**Comment by jamesray1** [comment]
It's just really tedious to have to go through all the commits, split them into separate branches and create separate PRs. There are a lot of commits that have independent changes, but then there are also a lot of cross-dependencies between commits, particularly with the hyperref package.

**Comment by jamesray1** [comment]
It also seems harder to work with Git when there are many branches.

Every time I make a change in Git to keep PRs short it'd be best to create the change in a separate branch with `git checkout` to the branch to duplicate, then `git checkout -b <describe-the-change>` then make the changes locally, then run Git push. It's easier to use Github, but Github isn't good when you need to cherry-pick commits.

**Comment by jamesray1** [comment]
Yoichi, I have a suggestion. Post a link in the readme to a comment that contains a link to my latest version of the paper, with a warning that this version has not been reviewed, approved, or merged. @pirapira

**Comment by pirapira** [comment]
@jamesray1 I cannot do that for the copyright reasons.

**Comment by jamesray1** [comment]
Even if my PR is CC0?

**Comment by pirapira** [comment]
@jamesray1 the original is not CC0.

**Comment by jamesray1** [comment]
Ah I see what you mean there is no license so by default it's all rights reserved.

**Pull request closed without merging**
