### PR TITLE
careful replacement of SHA3 with KECCAK

### PR DESCRIPTION
**Pull request by ethers**
Initial step for https://github.com/ethereum/EIPs/issues/59

### CODE REVIEW

**Comment by gavofyork** [comment]
happy to merge this, but i think it needs to happen only following an EIP ratifying the alteration in nomenclature.

**Comment by ethers** [comment]
Solidity now has an alias named `keccak256()`.  Does that help?
https://github.com/ethereum/EIPs/issues/59#issuecomment-252866229

**Comment by axic** [comment]
Shouldn't it be named `KECCAK256` instead?

**Comment by ethers** [comment]
I don't mind either way.  What would you prefer @gavofyork ?

**Comment by gavofyork** [comment]
i think "KECCAK" is fine as long as it's stated as the 256-bit variant somewhere at the beginning. (technically we used SHA3-256, but we always drop the "-256" suffix)

**Comment by gavofyork** [comment]
needs resolving

**Comment by gavofyork** [comment]
this seems to have made it into `master` - closing.

**Pull request closed without merging**
