### PR TITLE
Formatting packages.

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by pirapira** [comment]
Locally I get 
```

! Package csquotes Error: Unbalanced groups or invalid nesting.

See the csquotes package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2222 \end{document}
```

**Comment by jamesray1** [comment]
PS I will probably make changes gradually so that I can spend more time on the JS sharding implementation.

**Comment by jamesray1** [comment]
Requires #437.

**Comment by jamesray1** [comment]
@pirapira, the build ran 3 days ago and hasn't ran since #444 was merge.

Additionally, note the status message when you sign in to Travis:

This job ran on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this [on our blog](https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch) and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version.

**Comment by jamesray1** [comment]
Additionally, Trusty isn't actually included in the .travis.yml file, as well as files that it links to—build.sh and travis_deploy.sh, so I'm not sure if I should just add:
```
dist: trusty
group: deprecated-2017Q4
```
after `sudo: required`, but I will anyway.

**Comment by pirapira** [comment]
Restarted the build.

**Comment by jamesray1** [comment]
Well the failing build still says csquotes.sty, so installing texlive-latex-extra didn't help.

**Comment by jamesray1** [comment]
Not sure whether you have something else in mind other than adding the csquotes.sty (and maybe also others).

**Comment by pirapira** [comment]
@jamesray1 are you sure you've added `texlive-latex-extra` in this PR?

**Comment by jamesray1** [comment]
@pirapira why does it need to be added to this PR when it has already been merged? That doesn't seem very functional.

**Comment by jamesray1** [comment]
Anyway I added it, but it is still failing.

**Comment by pirapira** [comment]
@jamesray1 ProTip: when you rebase your branch on top of `ethereum/master`, you get working `csquote`.

**Comment by jamesray1** [comment]
@pirapira, OK that sounds like you've tested that.

But I'm confused, didn't I make this PR by editing the Paper.tex file in https://github.com/ethereum/yellowpaper, then adding another .travis.yml file with the extra `sudo apt install texlive-latex-extra`?

How would rebasing this branch then help with csquote working?

**Comment by jamesray1** [comment]
The error before was because csquotes.sty was missing, but now it is:
```
! Package csquotes Error: Unbalanced groups or invalid nesting.
See the csquotes package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2509 \end{document}
```
I remember seeing a commit that fixed up a " to a ``, so that might explain it.

**Comment by jamesray1** [comment]
My experience with git rebase hasn't been great.

This is the commit that I mentioned:
7fc31a65bdc3f50988d9b72f11487218b4b73b0d

**Pull request merged**
