### PR TITLE
Spurious Dragon: EIP155 replay protection

### PR DESCRIPTION
**Pull request by pirapira**
This follows https://github.com/ethereum/EIPs/issues/155 as part of the Spurious Dragon changes.

Since I've branched `homestead`, and this change has already been taken into the mainnet, this PR is on `master`.

### CODE REVIEW

**Comment by adamsmo** [comment]
Will this change also affect ECDSARECOVER precompiled contract?

**Comment by pirapira** [comment]
No, that did not happen.

**Comment by adamsmo** [comment]
maybe it should be noted in the yellow paper because this PR changes definition of ECDSARECOVER which is also used (I mean the name) in precompiled contract section

**Comment by pirapira** [comment]
I begin to see what you mean.  Let me investigate.

**Comment by pirapira** [comment]
I confirm that this PR changes the definition of `ECDSARECOVER`.

**Comment by pirapira** [comment]
I can also confirm that in `cpp-ethereum`, the precompiled contract did not change.  Thank you for pointing out.

**Comment by pirapira** [comment]
This PR should normalize the value of `v` before passing it into `ECDSARECOVER`.

**Comment by pirapira** [comment]
@adamsmo A similar specification error already happened back in the Homestead transition, so I'm trying to fix that https://github.com/ethereum/yellowpaper/pull/305.  Feel free to comment.

**Comment by pirapira** [comment]
This PR should target the `spurious-dragon` branch.

**Pull request closed without merging**
