### PR TITLE
Creating dependency files for the csquotes package, e.g. to use opening double quotes

### PR DESCRIPTION
**Pull request by jamesray1**
Related: https://github.com/ethereum/yellowpaper/issues/366. Required for any changes that use an opening double quote.

### CODE REVIEW

**Comment by jamesray1** [comment]
They are needed to use features related to quotations, such as using opening double quotes instead of two single quotes. 
I found them by searching for them when it mentioned them in but the failed Travis build.
https://ctan.org/tex-archive/macros/latex/contrib/csquotes
https://ctan.org/pkg/etoolbox?lang=en

**Comment by pirapira** [comment]
@jamesray1 even the plain `tex` can interpret `` (backquote repeated twice) as the opening-double-quote.

**Comment by pirapira** [comment]
The Ubuntu package `texlive-latex-extra` should also contain `csquotes.sty`.

**Comment by jamesray1** [comment]
Replaced by #444.

**Comment by jamesray1** [comment]
> @jamesray1 even the plain tex can interpret `` (backquote repeated twice) as the opening-double-quote.

Yoichi, I understand that, but some people may edit the document without being familiar with the LaTeX rule to use two single backticks as a double quote, and just use a double quote as an opening quote (which quite frankly, I find is an odd rule). So adding the csquotes package helps as a fix for that.

**Pull request closed without merging**
