### PR TITLE
\usepackage{hyperref}, clarifications, grammar, cross-referencing, citations, biblio extra refs and adding URLs to existing refs

### PR DESCRIPTION
**Pull request by jamesray1**
Merged commits in #327 then added citations for new references. Here are the items in that closed PR:
- [x] added citations for signing transactions with 4e10ea6. Details are in [this](https://github.com/ethereum/yellowpaper/pull/327#issuecomment-331042378) comment below.
- [x] ECDSARESTORE changed to ECDSARECOVER with 60ea6865340e20b68cd648f941d4e9941886d0fc.
- [x] link for ECDSA functions with 098adb8
- [x] footnote for ECDSAcerticom with 5f7f93b048dedacc8673463c92002c20ae7a5260.
- [x] added live URLs and archived URLs (where possible) for all references with ac5990dd2f4ec4c5694f4a130a52d4429f3828e8.

See each commit for the other changes.

### CODE REVIEW

**Comment by jamesray1** [comment]
The two builds differ after the line: "LaTeX Warning: Reference `app:signing' on page 4 undefined on input line 264." at 1028 for the [current build](https://travis-ci.org/ethereum/yellowpaper/builds/276173722?utm_source=github_status&utm_medium=notification) with \usepackage{hyperref} commented out and [this build](https://travis-ci.org/ethereum/yellowpaper/builds/276149781?utm_source=github_status&utm_medium=notification) for the previous commit with the only difference to the current commit being that the \usepackage{hyperref} line is there (not commented out).

**Comment by pirapira** [comment]
`pdflatex` is failing on the Travis build.

**Comment by jamesray1** [comment]
I forgot to add details for 8183130b49b7599ff97ebfba3599f2703ae28822. I made some grammar fixes. The ones that aren't shown clearly in the diff I am highlighting as follows:
- providing ``consumers'' with the ability
- though blocks do not store

**Comment by jamesray1** [comment]
For "Missing $ inserted", I found [this](https://stackoverflow.com/questions/2476831/getting-the-error-missing-inserted-in-latex#2476868).

**Comment by jamesray1** [comment]
Closing for the moment because I am still making changes. I will reopen it.

**Comment by jamesray1** [comment]
Actually I'm closing because I pulled `jamesray1:patch-2` to jamesray1:master.

**Pull request closed without merging**
