### PR TITLE
Edit details for Gavin Wood author header

### PR DESCRIPTION
**Pull request by jamesray1**
@gavofyork should approve this before merging.

### CODE REVIEW

**Comment by jamesray1** [comment]
@gavofyork should approve this before merging.

**Comment by nicksavers** [comment]
"Ethcore" did change into "Parity Technologies", so just that could be changed. No need to add *formerly*. And the part about contacting others can be left out. Just communicate through this repository and you should be fine.

**Comment by jamesray1** [comment]
Should I edit the footnote to say please communicate through the repo?

**Comment by nicksavers** [comment]
That's the standard method for developers which is to be understood.

**Comment by pirapira** [comment]
@jamesray1 README.md is one good place to describe how to contribute.

**Comment by nicksavers** [comment]
Closing because I don't think the information adds anything relevant to the paper. If @gavofyork wants the name of his company and/or e-mail address changed, he has the ability of doing it himself.

**Comment by jamesray1** [comment]
Fair enough.

**Pull request closed without merging**
