### PR TITLE
[consensus uncertain] EIP86: initial account abstraction

### LINKED ISSUE #231: EIP 86
This issue keeps track of following the adoption of https://github.com/ethereum/EIPs/issues/86 as part of the Metropolis changes https://github.com/ethereum/yellowpaper/issues/229.

### PR DESCRIPTION
**Pull request by pirapira**
When merged, this will fix #231 .

### CODE REVIEW

**Comment by pirapira** [comment]
So far I have implemented points 1. and 2. of https://github.com/ethereum/EIPs/issues/86

**Comment by chriseth** [comment]
`Interpret the signature (0, 0, 0) as signed by 2^{256}` does that mean that anyone can spend the balance at `2^{256}-1`?

**Comment by pirapira** [comment]
I believe so at the moment.

**Comment by pirapira** [comment]
I still might need to say "the nonce of 2 ** 256 is never incremented".

**Comment by chriseth** [comment]
We should probably also disable nonce-checking for that sender address.

**Comment by pirapira** [comment]
Nonce-checking?

**Comment by pirapira** [comment]
Now I see the nonce-checking.

**Comment by pirapira** [comment]
This one is the pull-request version of EIP https://github.com/ethereum/EIPs/pull/208

**Comment by pirapira** [comment]
I'm seeking clarification about the nonce increment https://github.com/ethereum/EIPs/pull/208#issuecomment-283363913

**Comment by pirapira** [comment]
* [ ] seek clarification about the case when some code already exists at the address https://github.com/ethereum/EIPs/pull/208#discussion_r103882311

**Comment by pirapira** [comment]
This PR will be adjusted and reopened on `metropolis`.

**Pull request closed without merging**
