### PR TITLE
\hyperlink{H__g}, etc.

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by pirapira** [comment]
Needs merge.  Skipping this one.

**Comment by jamesray1** [comment]
@fulldecent I don't know why you are are approving these changes and in other PRs with merge conflicts when there are still conflicts to be resolved.

**Comment by fulldecent** [comment]
Sorry for the confusion. I am reviewing based on a manual review of the diffs.

You're right. Instead I should be looking at the whole thing.

**Comment by jamesray1** [comment]
No worries, I forgive you.

**Comment by jamesray1** [comment]
@pirapira this should be good to merge now.

**Comment by pirapira** [comment]
@jamesray1 @fulldecent I will notice merge conflicts.  Thank you for your contributions.

**Pull request merged**
