### PR TITLE
Add a line break before a tx address so that it doesn't run over the …

### PR DESCRIPTION
**Pull request by jamesray1**
…margin.

### CODE REVIEW

**Comment by jamesray1** [comment]
Yes, it does, and for good reason. The address runs over the margin and edge of the page at the moment.

**Comment by pirapira** [comment]
Well, you'll need to move the `\\` every time the layout changes.

Please try https://ctan.org/pkg/seqsplit .

**Comment by jamesray1** [comment]
That works!

**Comment by jamesray1** [comment]
I did some more testing, and found that if the hypertarget is in a text-mode location, links to it work normally (they show the target line at the top of the page). However, if the hypertarget is in math mode (of any kind: in-line or in display-math or in equation arrays), then it will direct to the line after the target.

**Pull request merged**
