### PR TITLE
hypertargets for Ethash parameters

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
I have put every hypertarget before the line that it refers to, because when you are directed to the hypertarget, it actually displays the next line at the top of the screen. So to actually include the line you want to display, you need to have the target on the preceding line.

**Comment by pirapira** [comment]
That way, mistakes can happen when people insert lines.
```
A \target{C}\\
C
```
into
```
A \target{C} \\
B \\
C
```
Is there a good workaround?  Do all hyperref users tolerate this?

**Comment by jamesray1** [comment]
I don't know. [I have asked around](https://tex.stackexchange.com/questions/411987/how-to-fix-hypertargets-directing-links-to-the-line-after-the-target).

**Comment by pirapira** [comment]
Similar questions with answers

https://tex.stackexchange.com/questions/17057/hypertarget-seems-to-aim-a-line-too-low

https://tex.stackexchange.com/questions/2068/hyperlinks-to-a-bibliography-are-one-line-off

**Comment by jamesray1** [comment]
I will need to change all the hypertargets. Can we just merge as is? Hopefully people will move the hypertarget if they add lines.

**Comment by pirapira** [comment]
The future communication costs about line arrangement outweighs the current fix.

**Pull request merged**
