### PR TITLE
Rename uncle to aunt to reduce androcentrism

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**

### CODE REVIEW

**Comment by obscuren** [comment]
:+1:

**Comment by LefterisJP** [comment]
nice one :)

**Comment by thehighfiveghost** [comment]
:P

**Comment by alexvandesande** [comment]
The correct gender neutral term for Aunt and Uncle is "Ommer" according to [non-binary](http://nonbinary.org/wiki/Gender_neutral_language#Family_Terms).

**Comment by debris** [comment]
made my day :+1:

**Comment by chriseth** [comment]
I like this change. Such an innovative text should not be backward when it comes to encouraging diversity. Another solution would be to step away from the family tree analogy altogether and use a term like "branch" or similar.

**Pull request closed without merging**
